[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "walledai"
version = "4.5.1"
description = "A Python SDK for interacting with Walled AI"
readme = "README.md"
authors = [{ name = "Walled AI", email = "rishabh@walled.ai" }]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "aiohttp>=3.8.0",
    "typing_extensions>=4.0.0",
    "pandas>=1.3.0",
    "scikit-learn>=1.0.0"
]
[tool.setuptools]
package-dir = {"" = "src"}
[tool.setuptools.packages.find]
where = ["src"]